[package]
name = "ltsv"
version = "0.1.0"
authors = ["glaceef <masaki7322_art@yahoo.co.jp>"]
edition = "2018"

[dependencies]

[[example]]
name = "load"

[[example]]
name = "create"

[[example]]
name = "append"
